In [21]:
import numpy as np
import pandas as pd

# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [22]:
data = np.array(pd.read_csv('/Users/Administrator/Documents/Work/pylearn/Perceptron/data.csv',
                  header=None))

In [23]:
X = data[:,0:2]
y = data[:,2]
# print('X is ',X)
# print('y is ',y)

In [29]:
i = 50
X = data[i,0:2]
y = data[i,2]
print('X is ',X)
print('y is ',y)

X is  [0.5533 1.    ]
y is  0.0


In [30]:
np.random.seed(42)
W = np.array(np.random.rand(2,1))
b = np.random.rand(1)[0] + max(data[:,1])
learn_rate = 0.01
print('W is ',W)
print('b is ',b)
print('learn_rate is ',learn_rate)

W is  [[0.37454012]
 [0.95071431]]
b is  1.731993941811405
learn_rate is  0.01


In [31]:
prediction(X, W, b)

1

In [32]:
W 

array([[0.37454012],
       [0.95071431]])

In [33]:
learn_rate * X.reshape(2,1)

array([[0.005533],
       [0.01    ]])

In [35]:
W - learn_rate * X.reshape(2,1)

array([[0.36900712],
       [0.94071431]])

In [47]:
if prediction(X, W, b) == y:
    indicator =  0
elif (prediction(X, W, b) != y and prediction(X, W, b) == 0):
    indicator =  1
elif (prediction(X, W, b) != y and prediction(X, W, b) == 1):
    indicator = -1
print('indicator is = ',indicator)
W = W + indicator * learn_rate * X.reshape(2,1)
b = b + indicator * learn_rate
print('W is = ',W)
print('b is = ',b)

indicator is =  -1
W is =  [[0.36347412]
 [0.93071431]]
b is =  1.711993941811405


In [16]:
# ***** ACTUAL SUBMISSION *****

In [42]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(100):
            print('i = ',i)
            X_row = X[i,0:2]
            y_row = y[i]

            print('X_row is = ',X_row)
            print('y_row is = ',y_row)
            
            if prediction(X_row, W, b) == y_row:
                indicator =  0
            elif (prediction(X_row, W, b) != y_row and prediction(X_row, W, b) == 0):
                indicator =  1
            elif (prediction(X_row, W, b) != y_row and prediction(X_row, W, b) == 1):
                indicator = -1
            print('indicator is = ',indicator)
            W = W + indicator * learn_rate * X_row.reshape(2,1)
            b = b + indicator * learn_rate
            print('W is = ',W)
            print('b is = ',b)
            
    return W, b


In [46]:
# perceptronStep(X, y, W, b, learn_rate = 0.01)

In [19]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines
