In [1]:
import pandas as pd
import numpy as np
import random as random
import re as re          # regrex package for string splitting

In [2]:
data_in = pd.read_table('/Users/Administrator/Documents/Work/pylearn/Bayes/smsspamcollection/SMSSpamCollection',
                        sep='\t',
                        names = ['label','sms_message'])
# data_np = np.array(data_in)

In [3]:
# data_in_01Target = data_in
# data_in_01Target['label_01'] = np.where(data_in_01Target['label'] == 'spam',1,0)
# data_in_01Target

In [4]:
print('data_in is: ',type(data_in))
# print('data_np is: ',type(data_np))

data_in is:  <class 'pandas.core.frame.DataFrame'>


In [5]:
# data_np_1 = np.hstack((data_np,np.zeros((len(data_np),1))))

In [6]:
### Filter records corresponding to spam
# data_in.loc[data_in['sms_label'] == 'spam']

In [7]:
# data_in.loc[data_in['label'] == 'spam','sms_label_01'] = 1
# data_in.loc[data_in['label'] == 'ham' ,'sms_label_01'] = 0

In [8]:
# data_in

In [9]:
# help(map)

In [10]:
data_in['label'] = data_in.label.map({'ham': 0, 'spam': 1})

In [11]:
pd.set_option('display.max_colwidth', 80)

In [12]:
data_in

label  \
0         0   
1         0   
2         1   
3         0   
4         0   
...     ...   
5567      1   
5568      0   
5569      0   
5570      0   
5571      0   

                                                                          sms_message  
0     Go until jurong point, crazy.. Available only in bugis n great world la e bu...  
1                                                       Ok lar... Joking wif u oni...  
2     Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA ...  
3                                   U dun say so early hor... U c already then say...  
4                       Nah I don't think he goes to usf, he lives around here though  
...                                                                               ...  
5567  This is the 2nd time we have tried 2 contact u. U have won the £750 Pound pr...  
5568                                             Will ü b going to esplanade fr home?  
5569                        Pity, * was in mood for that. So...any other suggestions?  
5570  The guy did some bitching but I acted like i'd be interested in buying somet...  
5571                                                       Rofl. Its true to its name  

[5572 rows x 2 columns]

In [13]:
# BAG OF WORDS

In [26]:
documents = ['Hello, how are you!',
             'Win money, win from home.',
             'Call me now.',
             'Hello, Call hello you tomorrow?']

In [27]:
# Set to lowercase
lower_case_documents = []
for i in documents:
    i_before = i
    i = i.lower()
    print('from: ',i_before,', to: ',i)
    lower_case_documents.append(i)
print(lower_case_documents)

from:  Hello, how are you! , to:  hello, how are you!
from:  Win money, win from home. , to:  win money, win from home.
from:  Call me now. , to:  call me now.
from:  Hello, Call hello you tomorrow? , to:  hello, call hello you tomorrow?
['hello, how are you!', 'win money, win from home.', 'call me now.', 'hello, call hello you tomorrow?']


In [28]:
# help(split())

In [35]:
### Remove punctuation

# import string as string
sans_punctuation_documents = []
for i in lower_case_documents:
    i_before = i
    i = re.split('!|,|\?| ',i)
    i = [i for i in i if i != '']

    print('from: ',i_before,', to: ',i)
    sans_punctuation_documents.append(i)
# sans_punctuation_documents = sans_punctuation_documents

from:  hello, how are you! , to:  ['hello', 'how', 'are', 'you']
from:  win money, win from home. , to:  ['win', 'money', 'win', 'from', 'home.']
from:  call me now. , to:  ['call', 'me', 'now.']
from:  hello, call hello you tomorrow? , to:  ['hello', 'call', 'hello', 'you', 'tomorrow']


In [36]:
preprocessed_documents = sans_punctuation_documents
preprocessed_documents

[['hello', 'how', 'are', 'you'],
 ['win', 'money', 'win', 'from', 'home.'],
 ['call', 'me', 'now.'],
 ['hello', 'call', 'hello', 'you', 'tomorrow']]

In [39]:
sans_punctuation_documents

[['hello', 'how', 'are', 'you'],
 ['win', 'money', 'win', 'from', 'home.'],
 ['call', 'me', 'now.'],
 ['hello', 'call', 'hello', 'you', 'tomorrow']]

In [40]:
### Separate words 

preprocessed_documents = []
for i in sans_punctuation_documents:
    i_before = i
#     i = re.split('!',i)
#     i = [i for i in i if i != '']
    
    print('from ',i_before,', to ',i)
    preprocessed_documents.append(i)

from  ['hello', 'how', 'are', 'you'] , to  ['hello', 'how', 'are', 'you']
from  ['win', 'money', 'win', 'from', 'home.'] , to  ['win', 'money', 'win', 'from', 'home.']
from  ['call', 'me', 'now.'] , to  ['call', 'me', 'now.']
from  ['hello', 'call', 'hello', 'you', 'tomorrow'] , to  ['hello', 'call', 'hello', 'you', 'tomorrow']


In [32]:
# help(collections.Counter())

In [20]:
# help(pprint)

In [21]:
frequency_list = []
import pprint
from collections import Counter

for i in preprocessed_documents:
    x = collections.Counter(i)
    print(x)
    frequency_list.append(x)
pprint.pprint(frequency_list)

NameError: name 'preprocessed_documents' is not defined

In [ ]:
# Now conducting with Sci-Kit Learn built in functions

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
X = count_vector.fit(documents)

In [55]:
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [56]:
documents

['Hello, how are you!',
 'Win money, win from home.',
 'Call me now.',
 'Hello, Call hello you tomorrow?']

In [57]:
doc_names = count_vector.fit(documents).get_feature_names()
doc_names

['are',
 'call',
 'from',
 'hello',
 'home',
 'how',
 'me',
 'money',
 'now',
 'tomorrow',
 'win',
 'you']

In [58]:
doc_array = count_vector.transform(documents).toarray()
doc_array

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1]])

In [59]:
frequency_matrix = pd.DataFrame(data = doc_array,columns=doc_names)
frequency_matrix

are  call  from  hello  home  how  me  money  now  tomorrow  win  you
0    1     0     0      1     0    1   0      0    0         0    0    1
1    0     0     1      0     1    0   0      1    0         0    2    0
2    0     1     0      0     0    0   1      0    1         0    0    0
3    0     1     0      2     0    0   0      0    0         1    0    1

In [60]:
# X_train.head(5)

In [109]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_in['sms_message'], 
                                                    data_in['label'], 
                                                    random_state=1)

# print('Number of rows in the total set: {}'.format(data_in.shape[0]))
print('Number of rows in the train set: {}'.format(X_train.shape[0]))
print('Number of rows in the test  set: {}'.format(X_test.shape[0]))
# print('Train fraction is : ',X_train.shape[0] / data_in.shape[0])
print('\nX_train looks like :\n',X_train.head(4))
print('\ny_train looks like :\n',y_train.head(4))

Number of rows in the train set: 4179
Number of rows in the test  set: 1393

X_train looks like :
 710     4mths half price Orange line rental & latest camera phones 4 FREE. Had your ...
3740                                                         Did you stitch his trouser
2711    Hope you enjoyed your new content. text stop to 61610 to unsubscribe. help:0...
3155    Not heard from U4 a while. Call 4 rude chat private line 01223585334 to cum....
Name: sms_message, dtype: object

y_train looks like :
 710     1
3740    0
2711    1
3155    1
Name: label, dtype: int64


In [105]:

###--- Create frequency for training dataset

In [106]:
count_vector = CountVectorizer()

In [110]:
dat_train_names = count_vector.fit(X_train).get_feature_names()
print('Sample of names from \'dat_train_names\'  is: \n',sorted(random.sample(dat_train_names,10))
)
# dat_train_names

Sample of names from 'dat_train_names'  is: 
 ['8883', 'ah', 'forgiveness', 'full', 'get4an18th', 'papa', 'singing', 'stars', 'walls', 'wheellock']


In [112]:
dat_train_array = count_vector.transform(X_train).toarray()
print('Shape of train array is : \n', dat_train_array.shape )
dat_train_array

Shape of train array is : 
 (4179, 7456)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [115]:
freq_train_matrix = pd.DataFrame(data = dat_train_array,columns=dat_train_names)
# freq_train_matrix

In [116]:

###--- Create frequency for test dataset

In [117]:
count_vector = CountVectorizer()

In [120]:
# dat_test_names   = count_vector.fit(X_test).get_feature_names()
# dat_test_array   = count_vector.transform(X_test).toarray()
# freq_test_matrix = pd.DataFrame(columns = dat_test_names,
#                                 data    = dat_test_array)


In [50]:
### --- View Test Data --- 
# dat_test_names
# dat_test_array
# freq_test_matrix

In [121]:
training_data = count_vector.fit_transform(X_train)
# print(training_data)
# X_train

In [122]:
testing_data = count_vector.transform(X_test)
# print(testing_data)

In [123]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
# naive_bayes.fit()

In [124]:
naive_bayes.fit(training_data,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [125]:
naive_bayes.predict(testing_data)

array([0, 0, 0, ..., 0, 1, 0])

In [126]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [127]:
# help(f1_score)

In [128]:
print('Accuracy score: ', format(accuracy_score(y_test,naive_bayes.predict(testing_data))))
print('Precision score: ', format(precision_score(y_test,naive_bayes.predict(testing_data))))
print('Recall score: ', format(recall_score(y_test,naive_bayes.predict(testing_data))))
print('F1 score: ', format(f1_score(y_test,naive_bayes.predict(testing_data))))

Accuracy score:  0.9885139985642498
Precision score:  0.9720670391061452
Recall score:  0.9405405405405406
F1 score:  0.9560439560439562


In [236]:
# print(np.array(training_data[1]))

In [237]:
# A = training_data[1]
# print(A)